import { env } from 'cloudflare:workers';
import { NextResponse } from 'next/server';
import { getChatGPTUser } from '../../chatgpt-auth';

async function businessFor(ownerId:string,create=false){let b=await env.DB.prepare('SELECT id FROM businesses WHERE owner_id=? LIMIT 1').bind(ownerId).first<{id:number}>();if(!b&&create){await env.DB.prepare(`INSERT OR IGNORE INTO businesses (owner_id,name,slug,timezone,created_at) VALUES (?,'Espacio Bienestar',?,'America/Santiago',?)`).bind(ownerId,`espacio-${ownerId}`,Math.floor(Date.now()/1000)).run();b=await env.DB.prepare('SELECT id FROM businesses WHERE owner_id=? LIMIT 1').bind(ownerId).first<{id:number}>();}return b;}
async function seedDefaults(businessId:number){const db=env.DB;await db.batch([
  db.prepare(`INSERT OR IGNORE INTO services (business_id,name,description,mode,duration_minutes,price_clp,deposit_percent,active) VALUES (?,'Evaluación inicial','Primera sesión para conocer las necesidades del cliente.','presencial',60,35000,0,1)`).bind(businessId),
  db.prepare(`INSERT OR IGNORE INTO services (business_id,name,description,mode,duration_minutes,price_clp,deposit_percent,active) VALUES (?,'Sesión de seguimiento','Continuidad del proceso con objetivos definidos.','presencial',45,28000,0,1)`).bind(businessId),
  db.prepare(`INSERT OR IGNORE INTO services (business_id,name,description,mode,duration_minutes,price_clp,deposit_percent,active) VALUES (?,'Consulta online','Atención remota mediante videollamada.','online',45,25000,0,1)`).bind(businessId),
]);}
export async function GET(){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:'Debes iniciar sesión.'},{status:401});const b=await businessFor(user.userId,true);if(!b)return NextResponse.json({error:'No se pudo preparar el negocio.'},{status:500});await seedDefaults(b.id);const result=await env.DB.prepare(`SELECT s.id,s.name,s.description,s.mode,s.duration_minutes,s.price_clp,s.deposit_percent,s.active,COUNT(b.id) AS booking_count,COALESCE(SUM(CASE WHEN b.payment_status='paid' THEN b.amount_clp ELSE 0 END),0) AS paid_total FROM services s LEFT JOIN bookings b ON b.service_id=s.id AND b.status!='cancelled' WHERE s.business_id=? GROUP BY s.id ORDER BY s.active DESC,s.name COLLATE NOCASE`).bind(b.id).all();return NextResponse.json({services:result.results});}
function values(body:Record<string,unknown>){const name=String(body.name??'').trim();const description=String(body.description??'').trim();const mode=String(body.mode??'presencial');const duration=Number(body.durationMinutes);const price=Number(body.priceClp);const deposit=Number(body.depositPercent??0);if(!name||!['presencial','online','hibrido'].includes(mode)||!Number.isInteger(duration)||duration<15||duration>480||!Number.isInteger(price)||price<0||!Number.isInteger(deposit)||deposit<0||deposit>100)return null;return{name,description,mode,duration,price,deposit};}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:'Debes iniciar sesión.'},{status:401});const b=await businessFor(user.userId,true);if(!b)return NextResponse.json({error:'No se pudo preparar el negocio.'},{status:500});const data=values(await request.json() as Record<string,unknown>);if(!data)return NextResponse.json({error:'Revisa el nombre, duración, precio y abono.'},{status:400});const duplicate=await env.DB.prepare('SELECT id FROM services WHERE business_id=? AND name=?').bind(b.id,data.name).first();if(duplicate)return NextResponse.json({error:'Ya existe un servicio con ese nombre.'},{status:409});const result=await env.DB.prepare('INSERT INTO services (business_id,name,description,mode,duration_minutes,price_clp,deposit_percent,active) VALUES (?,?,?,?,?,?,?,1)').bind(b.id,data.name,data.description||null,data.mode,data.duration,data.price,data.deposit).run();return NextResponse.json({id:Number(result.meta.last_row_id),message:'Servicio creado correctamente.'},{status:201});}
export async function PATCH(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:'Debes iniciar sesión.'},{status:401});const b=await businessFor(user.userId);if(!b)return NextResponse.json({error:'Servicio no encontrado.'},{status:404});const body=await request.json() as Record<string,unknown>;const id=Number(body.id);if(!Number.isInteger(id))return NextResponse.json({error:'Servicio inválido.'},{status:400});if(typeof body.active==='boolean'){const result=await env.DB.prepare('UPDATE services SET active=? WHERE id=? AND business_id=?').bind(body.active?1:0,id,b.id).run();if(!result.meta.changes)return NextResponse.json({error:'Servicio no encontrado.'},{status:404});return NextResponse.json({message:body.active?'Servicio activado.':'Servicio pausado.'});}const data=values(body);if(!data)return NextResponse.json({error:'Revisa el nombre, duración, precio y abono.'},{status:400});const duplicate=await env.DB.prepare('SELECT id FROM services WHERE business_id=? AND name=? AND id!=?').bind(b.id,data.name,id).first();if(duplicate)return NextResponse.json({error:'Ya existe otro servicio con ese nombre.'},{status:409});const result=await env.DB.prepare('UPDATE services SET name=?,description=?,mode=?,duration_minutes=?,price_clp=?,deposit_percent=? WHERE id=? AND business_id=?').bind(data.name,data.description||null,data.mode,data.duration,data.price,data.deposit,id,b.id).run();if(!result.meta.changes)return NextResponse.json({error:'Servicio no encontrado.'},{status:404});return NextResponse.json({message:'Servicio actualizado correctamente.'});}
