import { env } from 'cloudflare:workers';
import { NextResponse } from 'next/server';
import { getChatGPTUser } from '../../chatgpt-auth';

async function businessFor(ownerId:string,create=false){let b=await env.DB.prepare('SELECT id FROM businesses WHERE owner_id=? LIMIT 1').bind(ownerId).first<{id:number}>();if(!b&&create){await env.DB.prepare(`INSERT OR IGNORE INTO businesses (owner_id,name,slug,timezone,created_at) VALUES (?,'Espacio Bienestar',?,'America/Santiago',?)`).bind(ownerId,`espacio-${ownerId}`,Math.floor(Date.now()/1000)).run();b=await env.DB.prepare('SELECT id FROM businesses WHERE owner_id=? LIMIT 1').bind(ownerId).first<{id:number}>();}return b;}
async function seed(businessId:number){const db=env.DB;await db.batch([db.prepare(`INSERT OR IGNORE INTO professionals (business_id,name,email,phone,role,color,active) VALUES (?,'Sofía Martínez','sofia@nexo.demo',NULL,'Especialista','#7559f2',1)`).bind(businessId),db.prepare(`INSERT OR IGNORE INTO professionals (business_id,name,email,phone,role,color,active) VALUES (?,'Martín Reyes','martin@nexo.demo',NULL,'Especialista','#30b995',1)`).bind(businessId)]);}
export async function GET(){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:'Debes iniciar sesión.'},{status:401});const b=await businessFor(user.userId,true);if(!b)return NextResponse.json({error:'No se pudo preparar el negocio.'},{status:500});await seed(b.id);const result=await env.DB.prepare(`SELECT p.id,p.name,p.email,p.phone,p.role,p.color,p.active,COUNT(b.id) AS booking_count,COALESCE(SUM(CASE WHEN b.payment_status='paid' THEN b.amount_clp ELSE 0 END),0) AS paid_total,COUNT(DISTINCT CASE WHEN b.starts_at>=? THEN b.id END) AS upcoming_count FROM professionals p LEFT JOIN bookings b ON b.professional_id=p.id AND b.status!='cancelled' WHERE p.business_id=? GROUP BY p.id ORDER BY p.active DESC,p.name COLLATE NOCASE`).bind(Math.floor(Date.now()/1000),b.id).all();return NextResponse.json({team:result.results});}
function values(body:Record<string,unknown>){const name=String(body.name??'').trim();const email=String(body.email??'').trim().toLowerCase();const phone=String(body.phone??'').trim();const role=String(body.role??'').trim();const color=String(body.color??'#7559f2');if(!name||!/^\S+@\S+\.\S+$/.test(email)||!role||!/^#[0-9a-f]{6}$/i.test(color))return null;return{name,email,phone,role,color};}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:'Debes iniciar sesión.'},{status:401});const b=await businessFor(user.userId,true);if(!b)return NextResponse.json({error:'No se pudo preparar el negocio.'},{status:500});const data=values(await request.json() as Record<string,unknown>);if(!data)return NextResponse.json({error:'Revisa nombre, correo, cargo y color.'},{status:400});const duplicate=await env.DB.prepare('SELECT id FROM professionals WHERE business_id=? AND (name=? OR email=?)').bind(b.id,data.name,data.email).first();if(duplicate)return NextResponse.json({error:'Ya existe un integrante con ese nombre o correo.'},{status:409});const result=await env.DB.prepare('INSERT INTO professionals (business_id,name,email,phone,role,color,active) VALUES (?,?,?,?,?,?,1)').bind(b.id,data.name,data.email,data.phone||null,data.role,data.color).run();return NextResponse.json({id:Number(result.meta.last_row_id),message:'Integrante agregado correctamente.'},{status:201});}
export async function PATCH(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:'Debes iniciar sesión.'},{status:401});const b=await businessFor(user.userId);if(!b)return NextResponse.json({error:'Integrante no encontrado.'},{status:404});const body=await request.json() as Record<string,unknown>;const id=Number(body.id);if(!Number.isInteger(id))return NextResponse.json({error:'Integrante inválido.'},{status:400});if(typeof body.active==='boolean'){const result=await env.DB.prepare('UPDATE professionals SET active=? WHERE id=? AND business_id=?').bind(body.active?1:0,id,b.id).run();if(!result.meta.changes)return NextResponse.json({error:'Integrante no encontrado.'},{status:404});return NextResponse.json({message:body.active?'Agenda activada.':'Agenda pausada.'});}const data=values(body);if(!data)return NextResponse.json({error:'Revisa nombre, correo, cargo y color.'},{status:400});const duplicate=await env.DB.prepare('SELECT id FROM professionals WHERE business_id=? AND (name=? OR email=?) AND id!=?').bind(b.id,data.name,data.email,id).first();if(duplicate)return NextResponse.json({error:'Otro integrante ya utiliza ese nombre o correo.'},{status:409});const result=await env.DB.prepare('UPDATE professionals SET name=?,email=?,phone=?,role=?,color=? WHERE id=? AND business_id=?').bind(data.name,data.email,data.phone||null,data.role,data.color,id,b.id).run();if(!result.meta.changes)return NextResponse.json({error:'Integrante no encontrado.'},{status:404});return NextResponse.json({message:'Integrante actualizado correctamente.'});}
